# Generated by Django 3.2.9 on 2021-11-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='details',
        ),
        migrations.AlterField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.profile'),
        ),
    ]
