# Generated by Django 3.2.9 on 2021-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211116_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blank_avatar.png', null=True, upload_to='profiles/'),
        ),
    ]
